{
	"version": 1589201569,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/camera-sheet0.png",
		"images/background1-sheet0.png",
		"images/background2-sheet0.png",
		"images/background3-sheet0.png",
		"images/background4-sheet0.png",
		"images/background5-sheet0.png",
		"images/ground.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"player idle (1).png",
		"player idle (2).png",
		"player idle (3).png",
		"player idle (4).png",
		"player idle (5).png",
		"player idle (6).png",
		"player idle (7).png",
		"player idle (8).png",
		"player idle (9).png",
		"player idle (10).png",
		"player idle (11).png",
		"player run-1.png",
		"player run-2.png",
		"player run-3.png",
		"player run-4.png",
		"player run-5.png",
		"player run-6.png",
		"player run-7.png",
		"player jump.png",
		"plx-1.png",
		"plx-2.png",
		"plx-3.png",
		"plx-4.png",
		"plx-5.png"
	]
}